#!/usr/bin/env zsh

function zpack-list() {
    local item
    if [[ -n $ZPACK_PLUGINS ]]; then
        __zpack_out_plain "Plugins:"
        for item in $ZPACK_PLUGINS; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $ZPACK_RELEASES ]]; then
        __zpack_out_plain "Releases:"
        for item in $ZPACK_RELEASES; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $ZPACK_SNIPPETS ]]; then
        __zpack_out_plain "Snippets:"
        for item in $ZPACK_SNIPPETS; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $ZPACK_BUNDLES ]]; then
        __zpack_out_plain "Bundles:"
        for item in $ZPACK_BUNDLES; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $ZPACK_BINARIES ]]; then
        __zpack_out_plain "Binaries:"
        for item in $ZPACK_BINARIES; do
            __zpack_out_plain "    $item"
        done
    fi
}

zpack-list $@
