#!/usr/bin/env zsh

function zpack-apply() {
    __zpack_cache var __ZPACK_PLUGINS
    __zpack_cache var __ZPACK_SNIPPETS
    __zpack_cache var __ZPACK_RELEASES
    __zpack_cache var __ZPACK_BUNDLES
    __zpack_cache var __ZPACK_BINARIES
    __zpack_cache stats_time cache_end

    ZPACK[stats_cache_compile_start]=$EPOCHREALTIME
    zpack-compile ${ZPACK[dir]}/zpack.zsh
    zpack-compile ${ZPACK[functions_dir]}/*
    zpack-compile ${ZPACK[cache_file]}
    ZPACK[stats_cache_compile_end]=$EPOCHREALTIME

    __zpack_apply

    ZPACK[stats_compinit_compile_start]=$EPOCHREALTIME
    zpack-compile ${ZPACK[compdump_path]}
    ZPACK[stats_compinit_compile_end]=$EPOCHREALTIME
}

zpack-apply $@
