#!/usr/bin/env zsh

function zpack-help() {
    __zpack_out_plain "usage: 'zpack [command] [options]'"
    __zpack_out_plain "    commands:"

    local cmd
    for cmd in ${(k)__ZPACK_CMDS}; do
        printf "        %-*s%s\n" 15 $cmd $__ZPACK_CMDS[$cmd]
    done

    __zpack_out_plain
    __zpack_out_plain "Please check the zsh completion to find out more about the options of commands."
}

zpack-help $@
