#!/usr/bin/env zsh

function zpack-reset() {
    local dir
    for dir in $ZPACK_BIN_DIR $ZPACK_CACHE_DIR; do
        __zpack_out "Deleting '$dir'"
        rm -drf "$dir"
    done

    __zpack_out "Deleting compiled files"
    rm -f $ZPACK_DIR/functions/*.zwc(N)
    rm -f $ZPACK_DIR/*.zwc(N)

    __zpack_out "Restarting shell"
    exec $SHELL
}

zpack-reset $@
