#!/usr/bin/env zsh

function zpack-list() {
    local item
    if [[ -n $__ZPACK_PLUGINS ]]; then
        __zpack_out_plain "Plugins:"
        for item in $__ZPACK_PLUGINS; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $__ZPACK_RELEASES ]]; then
        __zpack_out_plain "Releases:"
        for item in $__ZPACK_RELEASES; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $__ZPACK_SNIPPETS ]]; then
        __zpack_out_plain "Snippets:"
        for item in $__ZPACK_SNIPPETS; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $__ZPACK_BUNDLES ]]; then
        __zpack_out_plain "Bundles:"
        for item in $__ZPACK_BUNDLES; do
            __zpack_out_plain "    $item"
        done
    fi

    if [[ -n $__ZPACK_BINARIES ]]; then
        __zpack_out_plain "Binaries:"
        for item in $__ZPACK_BINARIES; do
            __zpack_out_plain "    $item"
        done
    fi
}

zpack-list $@
